#app.yaml
runtime: python39

env_variables:
  CLOUD_SQL_USERNAME: Jeet
  CLOUD_SQL_PASSWORD: Jeet13@90
  CLOUD_SQL_DATABASE_NAME: finalDB
  CLOUD_SQL_CONNECTION_NAME: newagent-pmyw:northamerica-northeast2:finalprojectdb

handlers:
  - url: /static
    static_dir: static